### ISSUE TITLE
missing files for the .py scripts

### ISSUE THREAD

**Issue by amscosta2022** [rohanshad/cfd_circulation_hf#1]
Hi Rohan
The following files are missing for the .py scripts : 
97_test.flow

Original aortic valve: av_converted.vtk as an ASCII vtk file 
Ring for the aortic root: edgefile.vtk as an ASCII vtk file
Developed by Alexander D. Kaiser, PhD

Would be great if you could upload them.
Best
Alex Costa - Universidade Estadual de Maringa - Brazil

**Comment by rohanshad** [comment]
Updated on todays commit for case # 97
